name = "alpha-calculator"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "ALPHA_KV"
id = "94e3ee8632404243b5b5e094d69363c1"
preview_id = "583f697c578e401daabdc1bbd3bf16a7"
